sudo: required

language: node

services:
  - docker

before_install:
  - docker-compose build

script:
  - sudo docker-compose run --rm new-ionic-image npm run lint
  - sudo docker-compose run --rm new-ionic-image npm run test-ci
