version: '2.1'

services:

  new-ionic-image:
    build: .
    container_name: new-ionic-image
    privileged: true
    volumes:
      - ./:/myApp:z
      - ~/.gradle:/root/.gradle
      - /dev/bus/usb:/dev/bus/usb
    tty: true
    stdin_open: true